development:
      adapter: postgresql
      encoding: unicode
      database: gw2itemsearch_development
      pool: 5
      username: 
      password:

test:
      adapter: postgresql
      encoding: unicode
      database: gw2itemsearch_test
      pool: 5
      username: 
      password:

production:
      adapter: postgresql
      encoding: unicode
      database: gw2itemsearch_production
      pool: 5
      username: 
      password:
